export const Fridges = [
  {
    name: "Lodówka + Zamrażarka",
    width: 110,
    height: 170,
    color: "white",
    id: "",
    energyClass: "E (roczny pobór: 264 kWh ≈ 163,68 zł)",
    price: 2500,
    isHighlighted: false,
  },
  {
    name: "Lodówka",
    width: 80,
    height: 170,
    color: "white",
    id: "",
    energyClass: "E (roczny pobór: 264 kWh ≈ 163,68 zł)",
    price: 1500,
    isHighlighted: false,
  },
  {
    name: "Zamrażarka",
    width: 70,
    height: 170,
    color: "white",
    id: "",
    energyClass: "E (roczny pobór: 264 kWh ≈ 163,68 zł)",
    price: 1000,
    isHighlighted: false,
  },
  {
    name: "Lodówka Slim",
    width: 50,
    height: 170,
    color: "white",
    id: "",
    energyClass: "E (roczny pobór: 264 kWh ≈ 163,68 zł)",
    price: 800,
    isHighlighted: false,
  },
];
